# Generated by Django 5.0.2 on 2024-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
