# Generated by Django 5.0.2 on 2024-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_verification_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=1, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
