# Generated by Django 5.0.2 on 2024-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsEditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('parent_categories', models.ManyToManyField(blank=True, related_name='child_categories', to='newsEditor.category')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='newsEditor.category'),
        ),
    ]
