# Generated by Django 5.0.2 on 2024-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsEditor', '0002_category_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
