# Generated by Django 5.0.2 on 2024-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsEditor', '0003_rename_description_news_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
