# Generated by Django 5.0.2 on 2024-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsEditor', '0005_news_card_title_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='card_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
